# Generated by Django 3.0.7 on 2020-06-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0004_userconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instauser',
            name='email_address',
        ),
    ]
