# Generated by Django 3.0.7 on 2020-06-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0005_remove_instauser_email_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_on',
            new_name='creation_date',
        ),
    ]
