# Generated by Django 3.0.7 on 2020-06-20 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0006_auto_20200619_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='creation_time',
        ),
    ]
